'use client';

import { useRouter } from 'next/navigation';
import { AppShell } from '@/components/shared/app-shell';
import { WeekSectionComponent } from '@/components/shared/week-section';
import { ProgressBar } from '@/components/shared/progress-bar';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Info, Clock, ArrowLeft } from 'lucide-react';
import { useChallenge } from '@/lib/challenge-context';
import { calculateProgress, calculateEstimatedTime, countAllTasks, formatMinutes } from '@/lib/challenge-utils';

// Static demo/dev preview only — shows the bundled sample plan from
// lib/mock-data.ts. Real challenges are generated by the AI and rendered at
// /challenges/[id]. This screen intentionally does NOT say "AI-generated".
export default function DemoPreviewPage() {
  const router = useRouter();
  const { demoChallenge } = useChallenge();

  const progress = calculateProgress(demoChallenge);
  const totalTime = calculateEstimatedTime(demoChallenge);
  const totalTasks = countAllTasks(demoChallenge);

  return (
    <AppShell showNav={false}>
      <div className="mx-auto max-w-3xl px-6 py-8 sm:py-12">
        <button
          onClick={() => router.push('/create/configure')}
          className="mb-6 flex items-center gap-1 text-sm font-medium text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to settings
        </button>

        <div className="mb-8">
          <div className="flex items-center gap-2 mb-3">
            <Badge variant="secondary" className="gap-1">
              <Info className="h-3 w-3" />
              Sample plan (demo data)
            </Badge>
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Here&apos;s an example of what a challenge looks like
          </h1>
          <p className="mt-2 text-muted-foreground">
            This is static sample data, not a generated plan. Use &quot;Create a
            challenge&quot; to generate a real one from your own goal.
          </p>
        </div>

        <div className="mb-8 rounded-2xl border border-border bg-card p-5 shadow-sm">
          <h2 className="text-xl font-bold tracking-tight">{demoChallenge.title}</h2>
          <p className="mt-1 text-sm text-muted-foreground">{demoChallenge.goal}</p>

          <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">
            <div>
              <p className="text-xs text-muted-foreground">Duration</p>
              <p className="text-lg font-bold">{demoChallenge.duration} days</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Total time</p>
              <p className="text-lg font-bold">{formatMinutes(totalTime)}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Tasks</p>
              <p className="text-lg font-bold">{totalTasks}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Completion</p>
              <p className="text-lg font-bold">{progress}%</p>
            </div>
          </div>

          <div className="mt-4">
            <ProgressBar value={progress} size="sm" />
          </div>
        </div>

        <div className="space-y-6 mb-8">
          {demoChallenge.weeks.map((week) => (
            <WeekSectionComponent key={week.id} week={week} isPreview />
          ))}
        </div>

        <Button
          onClick={() => router.push('/create')}
          size="lg"
          className="w-full text-base font-semibold rounded-xl shadow-lg shadow-primary/20"
        >
          <Clock className="mr-2 h-5 w-5" />
          Create your own challenge
        </Button>
      </div>
    </AppShell>
  );
}
